services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports: 
      - "5432:5432"
    networks:
      - backend
    environment: 
      POSTGRES_DB: database
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pw
    secrets:
      - db_pw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d database"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    build:
      context: ..
      dockerfile: docker/auth.Dockerfile
    ports:
      - "8001:8001"
    networks:
      - backend
    environment:
      TOKEN_EXPIRATION_MINUTES: 30
      DATABASE_URL: postgresql+psycopg2://postgres_user:@postgres/database
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - secret_key
      - db_pw


  app:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      AUTH_URL: http://auth:8001
      DATABASE_URL: postgresql+psycopg2://postgres_user:@postgres/database
    depends_on:
      auth:
        condition: service_started
      postgres:
        condition: service_healthy
    secrets:
      - db_pw

secrets:
  secret_key:
    file: ../secrets/secret_key
  db_pw:
    file: ../secrets/db_pw

networks:
  backend:

volumes:
  postgres_data: