apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: jhamed774/app-service:latest
        env:
        - name: AUTH_URL
          value: "http://auth:8001"
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_pw
        - name: DATABASE_URL
          value: "postgresql://postgres_user:$(DB_PW)@postgres/database"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key
        ports:
        - containerPort: 8000