apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: jhamed774/auth-service:latest
        env:
        - name: TOKEN_EXPIRATION_MINUTES
          value: "30"
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db_pw
        - name: DATABASE_URL
          value: "postgresql://postgres_user:$(DB_PW)@postgres/database"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key
        ports:
        - containerPort: 8001